Solution for second quest
Artur-Ws/pExIT pull request #8
Opened 2023-02-14 10:42 UTC by malmat94

Solution for second quest

2023-02-14 14:15 UTC, Artur-Ws requested changes
You do the same stuff in `multiplier` method and in `adder` method, maybe better solution will be get the numbers one time, for example in `main_process`, then just use them in `adder` and `multiplier` methods - According to DRY principle, there will be much less code without repetitions :)

2023-02-14 14:15 UTC, Artur-Ws commented on learning/basics/task2/MM-if_statement.py
> +            print("All right Nameless Noob, keep Your secrets...")
LOVE THAT ❤️

2023-02-14 14:15 UTC, Artur-Ws commented on learning/basics/task2/MM-if_statement.py
> +            pass
You don't need to put `else:` if it should only pass

2023-02-18 19:05 UTC, malmat94 commented
Yo, Artur, is there still anything wrong?

2023-02-20 15:34 UTC, Artur-Ws approved these changes

2023-02-20 15:34 UTC, merged